In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv("listings_Aug.csv")
df2 = pd.read_csv("listings_Jul.csv")
df3 = pd.read_csv("listings_Jun.csv")
df4 = pd.read_csv("listings_Sep.csv")

C:\Users\nsong\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (61,62,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\nsong\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (43,61,62,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [48]:
df = pd.concat([df1, df2, df3, df4])

In [51]:
df.shape

(194937, 106)

In [79]:
df_cleaned = df[["id", "summary","house_rules", "host_response_time", "host_response_rate", "neighbourhood_group_cleansed", "room_type", "accommodates", "bathrooms", "bedrooms", "beds", "price", "security_deposit", "cleaning_fee", "guests_included", "extra_people", "availability_365", "number_of_reviews", "review_scores_rating", "cancellation_policy", "reviews_per_month"]]
df_cleaned['summary']=df_cleaned['summary'].fillna('N')
df_cleaned['house_rules'] = df_cleaned['house_rules'].fillna('N')
df_cleaned.dropna(inplace=True)
df_cleaned.shape

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

(81233, 21)

In [80]:
df_cleaned.head()

,id,summary,house_rules,host_response_time,host_response_rate,neighbourhood_group_cleansed,room_type,accommodates,bathrooms,bedrooms,...,price,security_deposit,cleaning_fee,guests_included,extra_people,availability_365,number_of_reviews,review_scores_rating,cancellation_policy,reviews_per_month
0,2595,"Find your romantic getaway to this beautiful, ...","Make yourself at home, respect the space and t...",within a few hours,90%,Manhattan,Entire home/apt,2,1.0,0.0,...,$225.00,$350.00,$100.00,2,$0.00,288,46,95.0,strict_14_with_grace_period,0.39
4,5099,My large 1 bedroom apartment is true New York ...,• Check-in time is 2PM. • Check-out time is 12...,within a few hours,90%,Manhattan,Entire home/apt,2,1.0,1.0,...,$200.00,$300.00,$125.00,2,$100.00,127,75,89.0,strict_14_with_grace_period,0.60
8,5222,N,Please let me know if you will be staying with...,within a day,100%,Manhattan,Entire home/apt,2,1.0,1.0,...,$116.00,$500.00,$75.00,2,$15.00,322,94,95.0,strict_14_with_grace_period,0.74
9,5238,"Live like a New Yorker instead of a stuffy, ti...",No smoking in apartment. No Pets allowed. Ple...,within a few hours,100%,Manhattan,Entire home/apt,3,1.0,1.0,...,$150.00,$0.00,$40.00,2,$10.00,0,161,94.0,strict_14_with_grace_period,1.33
10,5295,N,"Dear Guests, Welcome to my apartment and I hop...",within a day,100%,Manhattan,Entire home/apt,2,1.0,1.0,...,$135.00,$450.00,$75.00,1,$0.00,1,53,93.0,strict_14_with_grace_period,0.42

In [81]:
df_cleaned['CheckDup'] = df_cleaned.duplicated(subset=None, keep='first')
df_cleaned[df_cleaned['CheckDup']==True].shape

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

(370, 22)

In [82]:
df_cleaned.drop_duplicates(keep='first',inplace=True)

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [83]:
df_final = df_cleaned

### Transform variables to construct feature

 Convert Summary and House_rules into length

In [84]:
df_final['summary_len'] = df_final['summary'].str.split().str.len()
df_final['houserules_len'] = df_final['house_rules'].str.split().str.len()

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [86]:
df_final["host_response_time"].unique()

array(['within a few hours', 'within a day', 'within an hour',
       'a few days or more'], dtype=object)

In [98]:
df_final['a few hours'] = (df_final['host_response_time'] == 'within a few hours')
df_final['a day'] = (df_final['host_response_time'] == 'within a day')
df_final['an hour'] = (df_final['host_response_time'] == 'within an hour')
df_final['a few days or more'] = (df_final['host_response_time'] == 'a few days or more')

df_final[['a few hours','a day','an hour','a few days or more']] = df_final[['a few hours','a day','an hour','a few days or more']].astype(int)

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\nsong\Anaconda3\lib\site-packages\pandas\core\frame.py:3137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [99]:
df_final['Manhattan'] = (df_final['neighbourhood_group_cleansed'] == 'Manhattan')
df_final['Brooklyn'] = (df_final['neighbourhood_group_cleansed'] == 'Brooklyn')
df_final['Queens'] = (df_final['neighbourhood_group_cleansed'] == 'Queens')
df_final['Bronx'] = (df_final['neighbourhood_group_cleansed'] == 'Bronx')
df_final['Staten_Island'] = (df_final['neighbourhood_group_cleansed'] == 'Staten Island')

df_final[['Manhattan','Brooklyn','Queens','Bronx','Staten_Island']] = df_final[['Manhattan','Brooklyn','Queens','Bronx','Staten_Island']].astype(int)
df_final['Others'] = df_final['Bronx'] + df_final['Staten_Island']

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\nsong\Anaconda3\lib\site-packages\pandas\core\frame.py:3137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [100]:
df_final['Entire home'] = (df_final['room_type'] == 'Entire home/apt')
df_final['Private_room'] = (df_final['room_type'] == 'Private room')
df_final['Shared_room'] = (df_final['room_type'] == 'Shared room')

df_final[['Entire home','Private_room','Shared_room']] = df_final[['Entire home','Private_room','Shared_room']].astype(int)

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\nsong\Anaconda3\lib\site-packages\pandas\core\frame.py:3137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [93]:
df_final['flexible'] = (df_final['cancellation_policy'] == 'flexible')
df_final['moderate'] = (df_final['cancellation_policy'] == 'moderate')
df_final['strict_14'] = (df_final['cancellation_policy'] == 'strict_14_with_grace_period')
df_final['strict_30'] = (df_final['cancellation_policy'] == 'super_strict_30')
df_final['strict'] = (df_final['cancellation_policy'] == 'strict')

df_final[['flexible','moderate','strict_14','strict_30','strict']] = df_final[['flexible','moderate','strict_14','strict_30','strict']].astype(int)
df_final.head()

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\nsong\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\nsong\Anaconda3\lib\site-packages\pandas\core\frame.py:3137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

,id,summary,house_rules,host_response_time,host_response_rate,neighbourhood_group_cleansed,room_type,accommodates,bathrooms,bedrooms,...,Staten_Island,Others,Entire home,Private_room,Shared_room,flexible,moderate,strict_14,strict_30,strict
0,2595,"Find your romantic getaway to this beautiful, ...","Make yourself at home, respect the space and t...",within a few hours,90%,Manhattan,Entire home/apt,2,1.0,0.0,...,0,0,1,0,0,0,0,1,0,0
4,5099,My large 1 bedroom apartment is true New York ...,• Check-in time is 2PM. • Check-out time is 12...,within a few hours,90%,Manhattan,Entire home/apt,2,1.0,1.0,...,0,0,1,0,0,0,0,1,0,0
8,5222,N,Please let me know if you will be staying with...,within a day,100%,Manhattan,Entire home/apt,2,1.0,1.0,...,0,0,1,0,0,0,0,1,0,0
9,5238,"Live like a New Yorker instead of a stuffy, ti...",No smoking in apartment. No Pets allowed. Ple...,within a few hours,100%,Manhattan,Entire home/apt,3,1.0,1.0,...,0,0,1,0,0,0,0,1,0,0
10,5295,N,"Dear Guests, Welcome to my apartment and I hop...",within a day,100%,Manhattan,Entire home/apt,2,1.0,1.0,...,0,0,1,0,0,0,0,1,0,0

In [142]:
df_done = df_final.drop(columns = ['summary','house_rules','host_response_time','Bronx','CheckDup','Staten_Island','strict','neighbourhood_group_cleansed','room_type','cancellation_policy'])
df_done.head()

,id,host_response_rate,accommodates,bathrooms,bedrooms,beds,price,security_deposit,cleaning_fee,guests_included,...,Brooklyn,Queens,Others,Entire home,Private_room,Shared_room,flexible,moderate,strict_14,strict_30
0,2595,90%,2,1.0,0.0,1.0,$225.00,$350.00,$100.00,2,...,0,0,0,1,0,0,0,0,1,0
4,5099,90%,2,1.0,1.0,1.0,$200.00,$300.00,$125.00,2,...,0,0,0,1,0,0,0,0,1,0
8,5222,100%,2,1.0,1.0,1.0,$116.00,$500.00,$75.00,2,...,0,0,0,1,0,0,0,0,1,0
9,5238,100%,3,1.0,1.0,2.0,$150.00,$0.00,$40.00,2,...,0,0,0,1,0,0,0,0,1,0
10,5295,100%,2,1.0,1.0,1.0,$135.00,$450.00,$75.00,1,...,0,0,0,1,0,0,0,0,1,0

In [143]:
df_done.dtypes

id                        int64
host_response_rate       object
accommodates              int64
bathrooms               float64
bedrooms                float64
beds                    float64
price                    object
security_deposit         object
cleaning_fee             object
guests_included           int64
extra_people             object
availability_365          int64
number_of_reviews         int64
review_scores_rating    float64
reviews_per_month       float64
summary_len               int64
houserules_len            int64
a few hours               int32
a day                     int32
an hour                   int32
a few days or more        int32
Manhattan                 int32
Brooklyn                  int32
Queens                    int32
Others                    int32
Entire home               int32
Private_room              int32
Shared_room               int32
flexible                  int32
moderate                  int32
strict_14                 int32
strict_30                 int32
dtype: object

In [144]:
df_done['price']=df_done['price'].str.replace('$','')
df_done['price']=df_done['price'].str.replace(',','')
df_done['price'] = df_done['price'].astype(float)
df_done['price'].head()

0     225.0
4     200.0
8     116.0
9     150.0
10    135.0
Name: price, dtype: float64

In [145]:
df_done['host_response_rate']=df_done['host_response_rate'].str.replace('%','')
df_done['host_response_rate'] = df_done['host_response_rate'].astype(float)
df_done['host_response_rate'] = df_done['host_response_rate']/100
df_done['host_response_rate'].head()

0     0.9
4     0.9
8     1.0
9     1.0
10    1.0
Name: host_response_rate, dtype: float64

In [146]:
df_done['security_deposit']=df_done['security_deposit'].str.replace('$','')
df_done['security_deposit']=df_done['security_deposit'].str.replace(',','')
df_done['security_deposit'].head()

0     350.00
4     300.00
8     500.00
9       0.00
10    450.00
Name: security_deposit, dtype: object

In [147]:
df_done['cleaning_fee']=df_done['cleaning_fee'].str.replace('$','')
df_done['cleaning_fee']=df_done['cleaning_fee'].str.replace(',','')
df_done['cleaning_fee'].head()

0     100.00
4     125.00
8      75.00
9      40.00
10     75.00
Name: cleaning_fee, dtype: object

In [148]:
df_done['extra_people']=df_done['extra_people'].str.replace('$','')
df_done['extra_people']=df_done['extra_people'].str.replace(',','')
df_done['extra_people'].head()

0       0.00
4     100.00
8      15.00
9      10.00
10      0.00
Name: extra_people, dtype: object

In [149]:
df_done.head()

,id,host_response_rate,accommodates,bathrooms,bedrooms,beds,price,security_deposit,cleaning_fee,guests_included,...,Brooklyn,Queens,Others,Entire home,Private_room,Shared_room,flexible,moderate,strict_14,strict_30
0,2595,0.9,2,1.0,0.0,1.0,225.0,350.00,100.00,2,...,0,0,0,1,0,0,0,0,1,0
4,5099,0.9,2,1.0,1.0,1.0,200.0,300.00,125.00,2,...,0,0,0,1,0,0,0,0,1,0
8,5222,1.0,2,1.0,1.0,1.0,116.0,500.00,75.00,2,...,0,0,0,1,0,0,0,0,1,0
9,5238,1.0,3,1.0,1.0,2.0,150.0,0.00,40.00,2,...,0,0,0,1,0,0,0,0,1,0
10,5295,1.0,2,1.0,1.0,1.0,135.0,450.00,75.00,1,...,0,0,0,1,0,0,0,0,1,0

## Regression Model

In [150]:
import sklearn 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

In [151]:
X = df_done.columns.drop('price','id')
y = df_done['price']

In [152]:
reg = LinearRegression().fit(X,y)

ValueError: could not convert string to float: 'strict_30'